<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LongGrid.Core\LongGrid.Core.csproj" />
    <ProjectReference
        Include="..\LongGrid.TaskbarWorker\LongGrid.TaskbarWorker.csproj"
        ReferenceOutputAssembly="false"
        OutputItemType="Content"
        CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\LongGrid.ThumbnailWorker\LongGrid.ThumbnailWorker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>

</Project>
