<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\LongGrid.Core\LongGrid.Core.csproj" />
    <ProjectReference Include="..\..\src\LongGrid.ThumbnailWorker\LongGrid.ThumbnailWorker.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="LongGrid.ThumbnailWorker" />
  </ItemGroup>

</Project>
