<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LongGrid.ThumbnailWorker</AssemblyName>
    <RootNamespace>LongGrid.ThumbnailWorker</RootNamespace>
  </PropertyGroup>

</Project>
